<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_1</name>
   <tag></tag>
   <elementGuidId>f34cca83-cd4c-4484-9d27-9d251648a315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frameset/frameset/frame[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>frame >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>3104eb03-6736-45af-a451-303b27422540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>frame_3.html</value>
      <webElementGuid>a6ec595a-b9c4-4921-9a8f-76d0fac3eacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frame[2]</value>
      <webElementGuid>01b27dfc-c0bd-4b6e-8603-427ede607697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset/frameset/frame[2]</value>
      <webElementGuid>65446e2e-a713-42cf-ae96-6a3e7cc96449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'frame_3.html']</value>
      <webElementGuid>3b323b78-5b8c-4ee7-b9f5-0e522220e45b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
